---
apiVersion: v1
kind: Service
metadata:
  name: artifactory
  namespace: immediate
  labels:
    app: artifactory
    group: artifactory-k8s
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8081
    name: ui
  selector:
    app: artifactory
